# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid
import zoom_demo.validate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=2000, null=True)),
                ('file', models.FileField(upload_to=zoom_demo.validate.models.upload_to)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('rendered', models.BooleanField(default=False)),
                ('form_name', models.CharField(choices=[(b'upload_form', b'File upload'), (b'url_form', b'Downloaded from URL'), (b'text_form', b'Pasted into textarea')], max_length=20, null=True)),
            ],
        ),
    ]
