# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default=b'default', max_length=200),
        ),
    ]
