# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0002_file_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
