# Generated by Django 2.1.2 on 2018-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoints',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
