# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='other',
            field=models.CharField(max_length=500),
        ),
    ]
