# Generated by Django 2.1.2 on 2018-11-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
        ('indicator', '0001_initial'),
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='file_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.FileSource'),
        ),
        migrations.AddField(
            model_name='filters',
            name='datapoints',
            field=models.ManyToManyField(related_name='filters', to='indicator.Datapoints'),
        ),
        migrations.AddField(
            model_name='filters',
            name='date_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.DateFormat'),
        ),
        migrations.AddField(
            model_name='filters',
            name='geolocations',
            field=models.ManyToManyField(to='geodata.Geolocation'),
        ),
        migrations.AddField(
            model_name='filters',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.FilterHeadings'),
        ),
        migrations.AddField(
            model_name='filters',
            name='metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.File'),
        ),
        migrations.AddField(
            model_name='filters',
            name='value_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.ValueFormat'),
        ),
        migrations.AddField(
            model_name='filterheadings',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.Indicator'),
        ),
        migrations.AddField(
            model_name='datapoints',
            name='date_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.DateFormat'),
        ),
        migrations.AddField(
            model_name='datapoints',
            name='geolocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.Geolocation'),
        ),
        migrations.AddField(
            model_name='datapoints',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.Indicator'),
        ),
        migrations.AddField(
            model_name='datapoints',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.File'),
        ),
        migrations.AddField(
            model_name='datapoints',
            name='value_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.ValueFormat'),
        ),
    ]
