# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterheadings',
            name='aggregation_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
