# Generated by Django 2.1.2 on 2018-10-29 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='datapoints',
        ),
        migrations.AddField(
            model_name='datapoints',
            name='filters',
            field=models.ManyToManyField(related_name='datapoints', to='indicator.Filters'),
        ),
        migrations.RemoveField(
            model_name='datapoints',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='datapoints',
            name='geolocation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geodata.Geolocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicator',
            name='file_source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='metadata.FileSource'),
            preserve_default=False,
        ),
    ]
