# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('indicator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatordatapoint',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='indicatordatapoint',
            name='date_format_id',
        ),
        migrations.RemoveField(
            model_name='indicatordatapoint',
            name='indicator_category_id',
        ),
        migrations.RemoveField(
            model_name='indicatordatapoint',
            name='indicator_id',
        ),
        migrations.RemoveField(
            model_name='indicatordatapoint',
            name='source_id',
        ),
        migrations.AddField(
            model_name='indicatordatapoint',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.Country'),
        ),
        migrations.AddField(
            model_name='indicatordatapoint',
            name='date_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicator.Time'),
        ),
        migrations.AddField(
            model_name='indicatordatapoint',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicator.Indicator'),
        ),
        migrations.AddField(
            model_name='indicatordatapoint',
            name='indicator_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorCategory'),
        ),
        migrations.AddField(
            model_name='indicatordatapoint',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorSource'),
        ),
    ]
