# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-09 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_auto_20170609_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='indicator.IndicatorCategory'),
        ),
    ]
