# Generated by Django 2.1.3 on 2019-04-10 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_delete_other_added_other_responden_and_other_cleaning_technique'),
        ('indicator', '0002_indicator_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='file',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='metadata.File'),
            preserve_default=False,
        ),
    ]
