# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_auto_20170123_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorsubgroup',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='indicatordatapoint',
            name='subgroup',
        ),
        migrations.DeleteModel(
            name='IndicatorSubgroup',
        ),
    ]
