# Generated by Django 2.1.2 on 2018-10-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_auto_20181030_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='date_formats',
        ),
        migrations.RemoveField(
            model_name='filters',
            name='value_formats',
        ),
        migrations.AddField(
            model_name='filters',
            name='date_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.DateFormat'),
        ),
        migrations.AddField(
            model_name='filters',
            name='value_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicator.ValueFormat'),
        ),
    ]
