# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_filesource_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesource',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
