# Generated by Django 2.1.3 on 2018-12-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0002_auto_20181126_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='filters',
            name='indicator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='indicator.Indicator'),
            preserve_default=False,
        ),
    ]
