# Generated by Django 2.1.3 on 2019-04-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_indicator_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.File'),
        ),
    ]
