# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_auto_20170123_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='measure_value',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
