# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-09 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_auto_20170609_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorcategory',
            name='unique_identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
