# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0003_auto_20170302_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.FileSource')),
            ],
        ),
    ]
