# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_filetags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='other',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
