# Generated by Django 2.1.3 on 2019-04-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_indicator_file_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='first_data_year',
            field=models.CharField(default='2005', max_length=200),
        ),
    ]
