# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0004_auto_20170124_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatordatapoint',
            old_name='country',
            new_name='country_id',
        ),
        migrations.RenameField(
            model_name='indicatordatapoint',
            old_name='date_format',
            new_name='date_format_id',
        ),
        migrations.RenameField(
            model_name='indicatordatapoint',
            old_name='file_source',
            new_name='file_source_id',
        ),
        migrations.RenameField(
            model_name='indicatordatapoint',
            old_name='indicator',
            new_name='indicator_id',
        ),
        migrations.RenameField(
            model_name='indicatordatapoint',
            old_name='source',
            new_name='source_id',
        ),
    ]
