# Generated by Django 2.1.3 on 2019-06-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_indicator_first_data_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='first_data_year',
            new_name='last_data_year',
        ),
    ]
