# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0005_auto_20171121_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
