# Generated by Django 2.1.10 on 2019-08-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0006_auto_20190618_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterheadings',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='filters',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
