# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0006_auto_20171127_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorcategory',
            name='unique_identifier',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
