# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0006_auto_20170124_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='country_id',
            field=models.ForeignKey(db_column=b'country_id', on_delete=django.db.models.deletion.CASCADE, to='indicator.Country'),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='date_format_id',
            field=models.ForeignKey(db_column=b'date_format_id', on_delete=django.db.models.deletion.CASCADE, to='indicator.Time'),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='file_source_id',
            field=models.ForeignKey(db_column=b'file_source_id', on_delete=django.db.models.deletion.CASCADE, to='indicator.FileSource'),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='indicator_category_id',
            field=models.ForeignKey(db_column=b'indicator_category', on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorCategory'),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='indicator_id',
            field=models.ForeignKey(db_column=b'indicator_id', on_delete=django.db.models.deletion.CASCADE, to='indicator.Indicator'),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='source_id',
            field=models.ForeignKey(db_column=b'source_id', on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorSource'),
        ),
    ]
