# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0007_auto_20170124_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='indicator_category_id',
            field=models.ForeignKey(db_column=b'indicator_category_id', on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorCategory'),
        ),
    ]
