# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0007_auto_20171128_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='date_value',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
