# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0007_indicatordatapoint_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='measure_value',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
