# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0007_auto_20170816_1446'),
        ('indicator', '0008_auto_20171208_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indicator',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_upload.FileSource'),
        ),
    ]
