# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0008_auto_20170418_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScatterData',
        ),
    ]
