# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0008_auto_20170124_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='date_value',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='measure_value',
            field=models.CharField(max_length=20),
        ),
    ]
