# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0009_auto_20171211_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='source',
            new_name='file_source',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
