# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0009_auto_20170124_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorDatapoint1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_value', models.CharField(max_length=20)),
                ('measure_value', models.CharField(max_length=20)),
                ('other', models.CharField(max_length=500)),
                ('country_id', models.ForeignKey(db_column=b'country_id', on_delete=django.db.models.deletion.CASCADE, to='indicator.Country')),
                ('date_format_id', models.ForeignKey(db_column=b'date_format_id', on_delete=django.db.models.deletion.CASCADE, to='indicator.Time')),
                ('file_source_id', models.ForeignKey(db_column=b'file_source_id', on_delete=django.db.models.deletion.CASCADE, to='indicator.FileSource')),
                ('indicator_category_id', models.ForeignKey(db_column=b'indicator_category_id', on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorCategory')),
                ('indicator_id', models.ForeignKey(db_column=b'indicator_id', on_delete=django.db.models.deletion.CASCADE, to='indicator.Indicator')),
                ('source_id', models.ForeignKey(db_column=b'source_id', on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorSource')),
            ],
        ),
    ]
