# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0010_indicatordatapoint1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatordatapoint1',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='indicatordatapoint1',
            name='date_format_id',
        ),
        migrations.RemoveField(
            model_name='indicatordatapoint1',
            name='file_source_id',
        ),
        migrations.RemoveField(
            model_name='indicatordatapoint1',
            name='indicator_category_id',
        ),
        migrations.RemoveField(
            model_name='indicatordatapoint1',
            name='indicator_id',
        ),
        migrations.RemoveField(
            model_name='indicatordatapoint1',
            name='source_id',
        ),
        migrations.DeleteModel(
            name='IndicatorDatapoint1',
        ),
    ]
