# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0010_auto_20171215_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='date_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
