# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0011_auto_20171220_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorFilterHeading',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='indicatorcategory',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='indicatorcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='indicatordatapoint',
            name='indicator_category',
        ),
        migrations.DeleteModel(
            name='IndicatorCategory',
        ),
        migrations.AddField(
            model_name='indicatorfilter',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorFilterHeading'),
        ),
        migrations.AddField(
            model_name='indicatorfilter',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.Indicator'),
        ),
        migrations.AddField(
            model_name='indicatorfilter',
            name='measure_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorDatapoint'),
        ),
    ]
