# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0011_auto_20170124_0320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='country_id',
            field=models.ForeignKey(db_column=b'country_id', on_delete=django.db.models.deletion.CASCADE, to='geodata.Country'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
