# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0011_auto_20171220_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorFilterHeading',
            fields=[
                ('heading_name', models.CharField(max_length=225, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.RemoveField(
            model_name='indicatorcategory',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='indicatorcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='indicatordatapoint',
            name='indicator_category',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='measure_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IndicatorCategory',
        ),
        migrations.AddField(
            model_name='indicatorfilters',
            name='datapoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorDatapoint'),
        ),
        migrations.AddField(
            model_name='indicatorfilters',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorFilterHeading'),
        ),
        migrations.AddField(
            model_name='indicatorfilters',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.Indicator'),
        ),
    ]
