# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0012_auto_20180116_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='indicatorfilters',
            name='datapoint',
        ),
        migrations.RemoveField(
            model_name='indicatorfilters',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='indicatorfilters',
            name='indicator',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='measure_value',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='IndicatorFilterHeading',
        ),
        migrations.DeleteModel(
            name='IndicatorFilters',
        ),
        migrations.AddField(
            model_name='indicatorcategory',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.Indicator'),
        ),
        migrations.AddField(
            model_name='indicatorcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='indicator.IndicatorCategory'),
        ),
        migrations.AddField(
            model_name='indicatordatapoint',
            name='indicator_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorCategory'),
        ),
    ]
