# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0012_auto_20170130_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='country_id',
            field=models.ForeignKey(blank=True, db_column=b'country_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.Country'),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='date_format_id',
            field=models.ForeignKey(blank=True, db_column=b'date_format_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicator.Time'),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='date_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='indicator_category_id',
            field=models.ForeignKey(blank=True, db_column=b'indicator_category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorCategory'),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='indicator_id',
            field=models.ForeignKey(blank=True, db_column=b'indicator_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicator.Indicator'),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='measure_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indicatordatapoint',
            name='source_id',
            field=models.ForeignKey(blank=True, db_column=b'source_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorSource'),
        ),
    ]
