# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0012_auto_20170130_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScatterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=255)),
                ('Indicator_1', models.CharField(max_length=255)),
                ('Indicator_1_value', models.CharField(max_length=20)),
                ('Indicator_2', models.CharField(max_length=255)),
                ('Indicator_2_value', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
    ]
