# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0012_auto_20180118_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorfilter',
            name='indicator',
        ),
    ]
