# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0013_remove_indicatorfilter_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='file_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='file_upload.FileSource'),
        ),
    ]
