# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-08 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0013_auto_20180118_1234'),
        ('indicator', '0011_auto_20180416_1342'),
    ]

    operations = [
    ]
