# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicator', '0014_auto_20180123_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='file_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_upload.FileSource'),
        ),
        migrations.AlterField(
            model_name='indicatorfilter',
            name='measure_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='indicator.IndicatorDatapoint'),
        ),
    ]
