# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0007_auto_20170816_1446'),
        ('indicator', '0015_auto_20180123_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorfilter',
            name='file_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_upload.FileSource'),
        ),
        migrations.AlterField(
            model_name='indicatorfilter',
            name='measure_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicator.IndicatorDatapoint'),
        ),
    ]
