# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0008_auto_20180130_1139'),
        ('indicator', '0016_auto_20180130_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorfilterheading',
            name='file_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_upload.FileSource'),
        ),
    ]
