# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import file_upload.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('in_progress', models.BooleanField(default=False)),
                ('source_url', models.URLField(max_length=2000, null=True)),
                ('file', models.FileField(upload_to=file_upload.models.upload_to)),
                ('file_name', models.CharField(default=b'default', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('rendered', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=1)),
                ('form_name', models.CharField(choices=[(b'upload_form', b'File upload'), (b'url_form', b'Downloaded from URL'), (b'text_form', b'Pasted into textarea')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileDtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype_name', models.CharField(max_length=500, null=True)),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_upload.File')),
            ],
        ),
        migrations.CreateModel(
            name='FileSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='data_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_upload.FileSource'),
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(to='file_upload.FileTag'),
        ),
    ]
