# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-12 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_auto_20170601_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='authorised',
            field=models.BooleanField(default=False),
        ),
    ]
