# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_auto_20170420_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDtypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.CharField(max_length=10)),
                ('line_no', models.IntegerField(max_length=8)),
                ('error_type', models.CharField(max_length=20)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload.File')),
            ],
        ),
    ]
