# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-15 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_file_authorised'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedtypes',
            name='dtype_dict_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
