# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_auto_20170420_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetag',
            old_name='tag',
            new_name='name',
        ),
    ]
