# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0005_auto_20170421_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedtypes',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='filedtypes',
            name='dtype',
        ),
        migrations.RemoveField(
            model_name='filedtypes',
            name='error_type',
        ),
        migrations.RemoveField(
            model_name='filedtypes',
            name='line_no',
        ),
        migrations.AddField(
            model_name='filedtypes',
            name='dtype_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filedtypes',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='file_upload.File'),
        ),
    ]
