# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-14 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0005_file_mapping_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='authorised',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
