# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0006_auto_20170421_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedtypes',
            name='dtype_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
