# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0006_auto_20170714_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='mapping_used',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
