# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0007_auto_20170816_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesource',
            name='id',
        ),
        migrations.AlterField(
            model_name='filesource',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
