# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-21 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0007_auto_20170421_1543'),
        ('file_upload', '0004_auto_20170421_1301'),
    ]

    operations = [
    ]
