# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0010_remove_filedtypes_validation_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
