# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0011_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
