# Generated by Django 2.1.3 on 2019-05-24 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_remove_file_mapping_used'),
        ('mapping', '0002_remove_unique_on_field_data_'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='error_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='mapping',
            name='file',
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='metadata.File'),
        ),
        migrations.AddField(
            model_name='mapping',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'INITIAL'),
                                            ('PENDING', 'PENDING'),
                                            ('RECEIVED', 'RECEIVED'),
                                            ('STARTED', 'STARTED'),
                                            ('SUCCESS', 'SUCCESS'),
                                            ('FAILURE', 'FAILURE'),
                                            ('REVOKED', 'REVOKED'),
                                            ('RETRY', 'RETRY')],
                                   default='INITIAL',
                                   max_length=10),
        ),
    ]
