# Generated by Django 2.1.3 on 2019-05-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_add_error_message_file_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
