# Generated by Django 2.1.3 on 2019-06-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_mapping_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='session_email',
            field=models.EmailField(blank=True,
                                    default=None,
                                    max_length=254,
                                    null=True),
        ),
    ]
