# Generated by Django 2.1.2 on 2018-10-23 11:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import metadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contains_subnational_data', models.BooleanField()),
                ('organisation', models.CharField(max_length=100)),
                ('maintainer', models.CharField(max_length=100)),
                ('date_of_dataset', models.DateField()),
                ('methodology', models.CharField(max_length=150)),
                ('define_methodology', models.TextField()),
                ('update_frequency', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('accessibility', models.CharField(choices=[('o', 'open'), ('p', 'private'), ('r', 'request')], max_length=100)),
                ('data_quality', models.CharField(max_length=1000)),
                ('number_of_rows', models.IntegerField(help_text='No. of rows within dataset')),
                ('number_of_rows_saved', models.IntegerField(help_text='No. of rows from dataset saved within ZOOM', null=True)),
                ('file_types', models.CharField(choices=[('csv', 'csv'), ('json', 'json')], max_length=100)),
                ('data_uploaded', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('original_file_location', models.CharField(max_length=300)),
                ('mapping_used', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('file_status', models.CharField(choices=[('1', 'Uploaded'), ('2', 'Error Correction'), ('3', 'Mapping'), ('4', 'Saved')], max_length=100)),
                ('datatypes_overview_file_location', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to=metadata.models.upload_to)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.Geolocation')),
            ],
        ),
        migrations.CreateModel(
            name='FileSource',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.FileSource'),
        ),
    ]
