# Generated by Django 2.1.2 on 2018-11-12 17:30

from django.db import migrations, models
import metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=500, upload_to=metadata.models.upload_to),
        ),
        migrations.AlterField(
            model_name='filesource',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
