# Generated by Django 2.1.2 on 2018-10-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='error_file_location',
            field=models.CharField(default='Todo', max_length=500),
            preserve_default=False,
        ),
    ]
