# Generated by Django 2.1.2 on 2018-11-01 16:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_heading_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
