# Generated by Django 2.1.3 on 2019-01-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydata',
            name='ask_sensitive',
            field=models.CharField(
                choices=[('Yes', 'Yes'), ('No', 'No'),
                         ("Don't know", "Don't know")],
                help_text=
                'It was possible for respondents to not answer certain questions if they found them to personal/sensitive?',
                max_length=100),
        ),
        migrations.AlterField(
            model_name='surveydata',
            name='staff_trained',
            field=models.CharField(
                choices=[('Yes', 'Yes'), ('No', 'No'),
                         ("Don't know", "Don't know")],
                help_text=
                'Staff was trained on how to ask the sensitive information to avoid influencing the respondent’s answer?',
                max_length=100),
        ),
    ]
