# Generated by Django 2.1.2 on 2018-11-09 01:52

from django.db import migrations, models
import metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_name_no_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=500, upload_to=metadata.models.upload_to),
        ),
    ]
