# Generated by Django 2.1.3 on 2018-12-10 10:38

from django.db import migrations, models
import metadata.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20181126_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to=metadata.models.upload_to),
        ),
    ]
