# Generated by Django 2.1.3 on 2019-05-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_auto_choices_field_initail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='mapping_used',
        ),
    ]
