# Generated by Django 2.1.3 on 2019-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_remove_file_mapping_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveydata',
            name='other_respondent',
        ),
        migrations.AlterField(
            model_name='surveydata',
            name='select_respondents',
            field=models.CharField(blank=True, default='', help_text='How did you select respondents?', max_length=200, null=True),
        ),
    ]
