# Generated by Django 2.1.3 on 2019-06-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_auto_20190611_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydata',
            name='how_many_respondents',
            field=models.CharField(
                blank=True,
                default='',
                help_text='How many respondents were interviewed/participated?',  # NOQA: E501
                max_length=200,
                null=True),
        ),
    ]
