# Generated by Django 2.1.2 on 2018-10-22 17:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ascii_name', models.CharField(blank=True, max_length=200, null=True)),
                ('center_longlat', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('wikipedia', models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.CharField(max_length=2, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('primary_name', models.BooleanField(default=False)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(blank=True, max_length=3, null=True)),
                ('numerical_code_un', models.IntegerField(blank=True, null=True)),
                ('dac_country_code', models.IntegerField(blank=True, null=True)),
                ('center_longlat', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('polygons', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('wikipedia', models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.CharField(max_length=2, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('capital_city', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_of', to='geodata.City')),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=200)),
                ('object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('country', 'country'), ('region', 'region'), ('subnational', 'subnational'), ('city', 'city'), ('pointbased', 'pointbased')], max_length=100)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='PointBased',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('center_longlat', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('comment', models.TextField()),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.Country')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=100)),
                ('center_longlat', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('polygons', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('wikipedia', models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.CharField(max_length=2, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubNational',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_3166_2', models.CharField(blank=True, max_length=2, null=True)),
                ('code_local', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('center_longlat', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('polygons', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('wikipedia', models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.CharField(max_length=2, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.Country')),
            ],
            options={
                'verbose_name_plural': 'admin1 regions',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.Region'),
        ),
        migrations.AddField(
            model_name='country',
            name='un_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='un_countries', to='geodata.Region'),
        ),
        migrations.AddField(
            model_name='country',
            name='unesco_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unesco_countries', to='geodata.Region'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.Country'),
        ),
    ]
