# Generated by Django 2.1.2 on 2018-11-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointbased',
            name='country',
        ),
        migrations.AddField(
            model_name='pointbased',
            name='subnational',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.SubNational'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
