# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryaltname',
            name='id',
        ),
        migrations.AlterField(
            model_name='countryaltname',
            name='name',
            field=models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
