# Generated by Django 2.1.3 on 2019-01-10 13:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_auto_20190110_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='polygons',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True,
                                                                    null=True,
                                                                    srid=4326),
        ),
    ]
