# Generated by Django 2.1.2 on 2018-11-08 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_auto_20181105_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointbased',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.Country'),
        ),
    ]
