# Generated by Django 2.1.2 on 2018-10-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_auto_20181016_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='primary_name',
            field=models.BooleanField(default=False),
        ),
    ]
