# Generated by Django 2.1.2 on 2018-10-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_country_primary_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='id',
        ),
        migrations.AddField(
            model_name='geolocation',
            name='geolocation_id',
            field=models.AutoField(default=None, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
