# Generated by Django 2.1.3 on 2019-01-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_auto_20190110_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='iso2',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
