# Generated by Django 2.1.3 on 2019-01-21 12:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0007_auto_20190115_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='center_longlat',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='polygons',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
