# Generated by Django 2.1.3 on 2019-02-18 15:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0008_added_center_longlat_and_polygon_to_geolocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id',
                 models.AutoField(editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ascii_name',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('center_longlat',
                 django.contrib.gis.db.models.fields.PointField(blank=True,
                                                                null=True,
                                                                srid=4326)),
                ('polygons',
                 django.contrib.gis.db.models.fields.GeometryField(blank=True,
                                                                   null=True,
                                                                   srid=4326)),
                ('wikipedia',
                 models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.CharField(max_length=2, null=True)),
                ('data_source',
                 models.CharField(blank=True, max_length=100, null=True)),
                ('country',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='geodata.Country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='polygons',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True,
                                                                    null=True,
                                                                    srid=4326),
        ),
    ]
