# Generated by Django 2.1.3 on 2019-02-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0009_added_province_and_and_added_polygon_to_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('country', 'name')},
        ),
    ]
