# Generated by Django 2.1.3 on 2019-02-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0010_udated_unique_together_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
