# Generated by Django 2.1.3 on 2019-02-21 17:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0012_added_province_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCode',
            fields=[
                ('id',
                 models.AutoField(editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('center_longlat',
                 django.contrib.gis.db.models.fields.PointField(blank=True,
                                                                null=True,
                                                                srid=4326)),
                ('polygons',
                 django.contrib.gis.db.models.fields.GeometryField(blank=True,
                                                                   null=True,
                                                                   srid=4326)),
                ('wikipedia',
                 models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.CharField(max_length=2, null=True)),
                ('data_source',
                 models.CharField(blank=True, max_length=100, null=True)),
                ('country',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='geodata.Country')),
            ],
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='type',
            field=models.CharField(choices=[('country', 'country'),
                                            ('region', 'region'),
                                            ('subnational', 'subnational'),
                                            ('city', 'city'),
                                            ('pointbased', 'pointbased'),
                                            ('province', 'province'),
                                            ('postcode', 'postcode')],
                                   max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='postcode',
            unique_together={('country', 'code')},
        ),
    ]
