# Generated by Django 2.1.3 on 2019-04-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0013_added_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
