# Generated by Django 2.1.3 on 2019-04-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0014_country_unique_iso2_iso3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='iso2',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='iso3',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
