# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 02:00
from __future__ import unicode_literals

import api.file.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=2000, null=True)),
                ('file', models.FileField(upload_to=api.file.models.upload_to)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('rendered', models.BooleanField(default=False)),
                ('form_name', models.CharField(choices=[(b'upload_form', b'File upload'), (b'url_form', b'Downloaded from URL'), (b'text_form', b'Pasted into textarea')], max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
